export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_DETAILS = 'USER_DETAILS';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';

export const BECOME_MENTOR_TRUE = 'BECOME_MENTOR_TRUE';
export const BECOME_MENTOR_FALSE = 'BECOME_MENTOR_FALSE';